module Promise {
  fun reject (input : a) : Promise(a, b) {
    ``
  }
}

component Main {
  fun test : Promise(Never, String) {
    sequence {
      greeting =
        Promise.reject("x")

      b =
        Promise.reject("y")

      a =
        Promise.reject(0)

      "blah"
    } catch String => a {
      "hello"
    } catch Number => a {
      "asd"
    }
  }

  fun render : Html {
    try {
      test()

      <div/>
    }
  }
}
--------------------------------------------------------------------------------
const B = new(class {
  c(f) {
    return
  }
})

class A extends Component {
  a() {
    return (async () => {
      let _ = null

      try {
        let b = await (async () => {
          try {
            return await B.c(`x`)
          } catch (_error) {
            let a = _error
            _ = `hello`
            throw new DoError()
          }
        })()

        let d = await (async () => {
          try {
            return await B.c(`y`)
          } catch (_error) {
            let a = _error
            _ = `hello`
            throw new DoError()
          }
        })()

        let e = await (async () => {
          try {
            return await B.c(0)
          } catch (_error) {
            let a = _error
            _ = `asd`
            throw new DoError()
          }
        })()

        _ = await `blah`
      } catch (_error) {
        if (!(_error instanceof DoError)) {
          console.warn(`Unhandled error in sequence expression:`)
          console.warn(_error)
        }
      }

      return _
    })()
  }

  render() {
    return (() => {
      this.a()

      return _createElement("div", {})
    })()
  }
}

A.displayName = "Main"
